version: '3'
services:
  go-server:
    image: gocd/gocd-server:v17.4.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./cruise-config.xml:/godata/config/cruise-config.xml
      - ./plugins:/godata/plugins/external/
    links:
      - git-daemon
  go-agent:
    build:
      context: .
      dockerfile: Dockerfile-go-agent
    environment:
      - GO_SERVER_URL=https://go-server:8154/go
      - AGENT_AUTO_REGISTER_KEY=388b633a88de126531afa41eff9aa69e
    links:
      - go-server
  git-daemon:
    image: bankiru/git-daemon
    ports:
      - "9418:9418"
    volumes:
      - ../go-pipeline-configs:/git
