pipelines:
  TheMet:
    group: applications
    materials:
      mygit:
        git: https://github.com/sebradloff/the-met.git
    stages:
      - UnitTest:
          clean_workspace: true
          jobs:
            UnitTest:
              tasks:
                - script: ./gradlew clean test
      - Build:
          clean_workspace: true
          jobs:
            Build:
              artifacts:
               - build:
                   source: build/libs/met-service-0.0.1-SNAPSHOT.jar
                   destination: builds
              tabs:
                builds: builds
              tasks:
                - script: ./gradlew clean build -x test
