pipelines:
  MovieSurfer:
    group: applications
    materials:
      mygit:
        git: https://github.com/sebradloff/movie-surfer.git
    stages:
      - build:
          jobs:
            inside:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Hello World"
